- name: create user accounts for all our servers
  hosts: managed
  become: true

  vars_files:
    - quiz-Secret.yml
  tasks:
    - name: Creating user from secret.yml
      user:
        name: "{{username}}"
        password: "{{passwd | password_hash('sha512')}}"
